### appspec.yaml ####
version: 0.0
os: linux
files:
  - source: /dist
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 120
      runas: root
