### appspec.yaml ####
version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 120
      runas: root