### appspec.yml ####
version: 0.0
os: linux
files:
  - source: /dist/angular-devops
    destination: /var/www/angular-frontend-dist
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 120
      runas: root
