version: 0.2

phases:
  install:
    commands:
      # Update libs
      - echo "Hiii"
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
  #post_build:
   # commands:
    #  - aws s3 sync ./dist/angular-devops s3:// --acl 'public-read' --delete
artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/after.sh'
  secondary-artifacts:
    artifact1:
      files:
        - '**/*.html'
        - '**/*.js'
        - '**/*.css'
        - '**/*.ico'
      discard-paths: yes
      base-directory: 'dist/angular-devops' 


