version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
      - npm run test:ci
  post_build:
    commands:
      - zip -r s3-artifacts.zip scripts appspec.yml dist/angular-devops
      - aws s3 cp ./s3-artifacts.zip s3://angular-devops-ci-cd 
#artifacts:
 # files:
  #  - 'appspec.yml'
   # - 'scripts/after.sh'
   # - 'dist/angular-devops/**/*' 
  #discard-paths: yes
  #base-directory: 'dist/angular-devops' 


